Invalidate CloudFront after deploy and hold until invalidation is not in progress.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,6 +68,16 @@ jobs:
             eval $(~/terraform/terraform -chdir=../../../terraform output -json | jq -r 'to_entries | map({key: .key | ascii_upcase, value: .value.value, type: .value.value | type}) | map(select(.type == "string" or .type == "number" or .type == "boolean")) | map("TF_OUT_\(.key)=\(.value)") | join("\n")')
             eval $(aws sts assume-role --role-arn ${TF_OUT_UPLOAD_ROLE_ARN} --role-session-name docs | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\(.AccessKeyId)\nexport AWS_SECRET_ACCESS_KEY=\(.SecretAccessKey)\nexport AWS_SESSION_TOKEN=\(.SessionToken)\n"')
             aws s3 sync . s3://${TF_OUT_DOCS_BUCKET_NAME} --delete --exclude=robots.txt
+            INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${TF_OUT_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*" --query Invalidation.Id --output text)
+            echo "Created CF Invalidation ${INVALIDATION_ID}"
+            while true; do
+              sleep 15
+              INVALIDATION_STATUS=$(aws cloudfront get-invalidation --distribution-id ${TF_OUT_CLOUDFRONT_DISTRIBUTION_ID} --id ${INVALIDATION_ID} --query Invalidation.Status --output text)
+              echo "Invalidation is ${INVALIDATION_STATUS}"
+              if ! [ $INVALIDATION_STATUS = "InProgress" ]; then
+                break
+              fi
+            done
       - slack/notify:
           event: pass
           template: basic_success_1
